name: W Corporate
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Technology for the Future
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2560133058577776
  lightness: 0.16740310261957347
  saturation: 0.769048448652029
  rhythmicContrast: 0.768832904053852
purpose: []
